# ANDRIX ® 2025-2026 🤙
# 
# Generate 3D textures for Unity out of voxel cubes, sph tracers or pointcloud files
#
# Klodu comes from Klodo, the japanese name of Final Fantasy VII character Cloud
# First source data from CRAL - Centre de Recherche Astrophysique de Lyon
# Later used for other data sources, mostly the RAMSES User Meeting 2026 in Seoul at Yonsei University

import math
import random
import os # for Fortran .dat
import numpy as np # for .npy & Fortran .dat
from scipy.io import FortranFile # for Fortran .dat
import datetime

error_start = "\033[91m"
error_end = "\033[0m"

def remap (input, source_min, source_max, target_min, target_max, clamp_mode):
    if (clamp_mode & (input < source_min)):
        return target_min
    elif (clamp_mode & (input > source_max)):
        return target_max
    else:
        return target_min + (target_max - target_min) * (input - source_min) / (source_max - source_min)

def write_unity_header (destination_file, file_name, base_size, testing_density, dimensionality, quality):
    
    actual_size = math.floor(base_size * testing_density)
    
    data_size_scale = 0
    encoding = ""
    
    if ((quality == "low") & (dimensionality == 1)):
        encoding = "R8"
    elif ((quality == "high") & (dimensionality == 1)):
        encoding = "R16"
    elif ((quality == "low") & (dimensionality == 2)):
        encoding = "RG16"
    elif ((quality == "high") & (dimensionality == 2)):
        encoding = "RG32"
    elif ((quality == "low") & (dimensionality == 3)):
        encoding = "RGB24"
    elif ((quality == "high") & (dimensionality == 3)):
        encoding = "RGB48"
    
    if (quality == "low"):
        data_size_scale = 1
    elif (quality == "high"):
        data_size_scale = 2
    else:
        print(error_start + "[write_unity_header] Error - unknown quality: " + quality + error_end)
        return None
        
    data_size = data_size_scale * dimensionality * (actual_size ** 3)
    
    # RGBAFloat -> "23" (values extracted from Texture3D files generated by Unity with various TextureFormat values, as of 2025 (Unity 6.0))
    data_format = ""
    if (encoding == "R8"):
        data_format = "5"
    elif (encoding == "R16"):
        data_format = "21"
    elif (encoding == "RG16"):
        data_format = "6"
    elif (encoding == "RG32"):
        data_format = "22"
    elif (encoding == "RGB24"):
        data_format = "7"
    elif (encoding == "RGB48"):
        data_format = "23"
    else:
        print(error_start + "[write_unity_header] Error - unknown encoding: " + encoding + error_end)
    
    destination_file.write("%YAML 1.1\n")
    destination_file.write("%TAG !u! tag:unity3d.com,2011:\n")
    destination_file.write("--- !u!117 &11700000\n")
    destination_file.write("Texture3D:\n")
    destination_file.write("  m_ObjectHideFlags: 0\n")
    destination_file.write("  m_CorrespondingSourceObject: {fileID: 0}\n")
    destination_file.write("  m_PrefabInstance: {fileID: 0}\n")
    destination_file.write("  m_PrefabAsset: {fileID: 0}\n")
    destination_file.write("  m_Name: " + file_name + "\n")
    destination_file.write("  m_ImageContentsHash:\n")
    destination_file.write("    serializedVersion: 2\n")
    destination_file.write("    Hash: 00000000000000000000000000000000\n")
    destination_file.write("  m_IsAlphaChannelOptional: 0\n")
    destination_file.write("  serializedVersion: 4\n")
    destination_file.write("  m_ColorSpace: 0\n")
    destination_file.write("  m_Format: " + data_format + "\n")
    destination_file.write("  m_Width: " + str(actual_size) + "\n")
    destination_file.write("  m_Height: " + str(actual_size) + "\n")
    destination_file.write("  m_Depth: " + str(actual_size) + "\n")
    destination_file.write("  m_MipCount: 1\n")
    destination_file.write("  m_DataSize: " + str(data_size) + "\n")
    destination_file.write("  m_TextureSettings:\n")
    destination_file.write("    serializedVersion: 2\n")
    destination_file.write("    m_FilterMode: 1\n")
    destination_file.write("    m_Aniso: 1\n")
    destination_file.write("    m_MipBias: 0\n")
    destination_file.write("    m_WrapU: 1\n")
    destination_file.write("    m_WrapV: 1\n")
    destination_file.write("    m_WrapW: 1\n")
    destination_file.write("  m_UsageMode: 0\n")
    destination_file.write("  m_IsReadable: 1\n")
    destination_file.write("  image data: " + str(data_size) + "\n")
    destination_file.write("  _typelessdata: ")

def write_unity_footer (destination_file):
    destination_file.write("\n")
    destination_file.write("  m_StreamData:\n")
    destination_file.write("    serializedVersion: 2\n")
    destination_file.write("    offset: 0\n")
    destination_file.write("    size: 0\n")
    destination_file.write("    path: \n")

def parse_int_to_formatted_hex (value, quality):
    # Expected format by Unity R16 tex is a bit effed-up
    # See, if color is of average intensity (min is 0000 max is ffff), you would expect something like 8803 or 88af without much difference
    # Here, Unity reads the two end characters before the two first ones, so the actual displayed intensities will be reversing the stacks of 2, so: 0388 and af88
    # Resulting in intensities of ~0% and ~70%...
    # Took me ~16h to figure it all out
    
    # Unity R8 format reads hex values in natural order (fa is almost white, 80 middle, 0e almost black)
    
    hex_value = hex(int(value))[2:] # Remove '0x' of hexadecimal notation
    
    if (quality == "high"):
        hexlen = len(str(hex_value)) # Make sure we always have 4 characters
        if (hexlen == 1):
            hex_value = "000" + str(hex_value)
        elif (hexlen == 2):
            hex_value = "00" + str(hex_value)
        elif (hexlen == 3):
            hex_value = "0" + str(hex_value)
        elif (hexlen == 4):
            hex_value = hex_value
        else:
            print(error_start + "[parse_int_to_formatted_hex] Sir we have a serious problem here, one hex value is either to short or too long! (high quality encoding)" + error_end)
            
        # Now reverse the stacks of 2 for Unity R16 & RGB48 formats
        hex_value = hex_value[2] + hex_value[3] + hex_value[0] + hex_value[1]
            
    elif (quality == "low"):
        hexlen = len(str(hex_value)) # Make sure we always have 2 characters
        if (hexlen == 1):
            hex_value = "0" + str(hex_value)
        elif (hexlen == 2):
            hex_value = hex_value
        else:
            print(error_start + "[parse_int_to_formatted_hex] Sir we have a serious problem here, one hex value is either to short or too long! (low quality encoding)" + error_end)
    
    return hex_value

def round_to_n(x, n):
    return 0 if (x == 0) else round(x, -int(math.floor(round(math.log10(abs(x)) - n + 1))))

def prepend_zeros (value, target_length):
    result = value
    size = len(str(value))
    for i in range(0, target_length - size):
        result = "0" + str(result)
        
    return result

def prepare_data_cube (source_file, file_type_token, dimensionality):
    
    if (file_type_token == "NUMPY"):
        data = np.load(source_file)
        
        print("Data shape is " + str(data.shape) + " with a total of " + str(data.size) + " elements.")
        
        return data
        
    elif (file_type_token == "DAT"):
        f = FortranFile(os.path.expanduser(source_file), 'r')
        
        sx, sy, sz = f.read_ints(np.int32) # just the size values
        data = f.read_reals(np.float32).reshape((sx, sy, sz, dimensionality), order='F')
        f.close()
        
        return data

    elif (file_type_token == "HDF5"):
        import h5py
        
        with h5py.File(source_file, "r") as f:
            # List all keys
            keys = list(f.keys())

            # Reorder keys to have x, y and z first if they exist
            for dim in ["z", "y", "x"]:
                if dim in keys:
                    keys.remove(dim)
                    keys.insert(0, dim)

            print("Keys: %s" % keys)
            
            # Load all datasets and stack them
            datasets = [np.array(f[key]) for key in keys]
            data = np.column_stack(datasets) if len(datasets) > 1 else np.array(datasets[0])
        
        print("Data shape is " + str(data.shape) + " with a total of " + str(data.size) + " elements.")
        return data
        
    else:
        print("[prepare_data_cube(...)] Unknown file type token: " + file_type_token)
        
        return False

# Create Unity 3D texture out of data cube
# input data cube should have implicit xyz just by the order of storage
# order of sequence (x, y or z) does not matter as we can always rotate the cube in the final visualization
#
# 'dimensionality' of 1 generates a 3D texture with "R" signel channel
# 'dimensionality' of 3 generates a 3D texture with "RGB" channels
# 1-dimension low quality intensities are exported to 8-bit single-channel 3D-texture, TextureFormat.R8 in Unity
# 1-dimension high quality intensities are exported to 16-bit single-channel 3D-texture, TextureFormat.R16 in Unity
# 3-dimension low quality intensities are exported to 3 x 8-bit RGB 3D-textures, TextureFormat.RGB24 in Unity
# 3-dimension high quality intensities are exported to 3 x 16-bit RGB 3D-textures, TextureFormat.RGB48 in Unity
def klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning):
    
    # Testing mode inits
    testing_density = min(1, testing_density) # Make sure it don't go krazy (> 1)
    testing_value = round(1/testing_density)
    
    # Various inits
    log_ratio = "all of " if testing_value == 1 else ("1 in " + str(testing_value ** 3) + " of all ")
    dimensionality = len(dimensions)
    
    # Prepare output file name
    dest_file_name = dest_file_name + ("-HQ" if quality == "high" else "-LQ")
    dest_file_name = dest_file_name + ("" if testing_value == 1 else ("-1-in-" + str(testing_value)))
    
    # Hello
    print("Starting work on data cube " + dest_file_name + "...")
    print("type: " + file_type_token + ", size: " + str(size) + ", dimensions: " + str(dimensions) + ", minmaxs: " + str(minmaxs) + ", quality: " + quality + ", testing density: 1 in " + str(testing_value) + "³ == 1 in " + str(testing_value ** 3) + ", number of logs: " + str(nb_logs))
    
    # Load data cube
    data = prepare_data_cube(source_file, file_type_token, dimensionality)
    
    # Prepare export file
    destination_file = open("output/" + dest_path + dest_file_name + ".asset", "w")
    
    # Generate Unity header
    base_size = data.shape[0]
    base_count = base_size * base_size * base_size
    actual_count = math.floor(base_count * (testing_density ** 3))
    write_unity_header(destination_file, dest_file_name, base_size, testing_density, dimensionality, quality)
    
    # Check if each cell contains a scalar or an array (some have only 1 value but still in an array... with 1 value)
    is_cell_array = not np.isscalar(data[0][0][0])
    
    # Track time taken
    start_time = datetime.datetime.now()
    
    # Compute ranges (related to testing_density)
    x_range = math.floor(data.shape[0] * testing_density)
    y_range = math.floor(data.shape[1] * testing_density)
    z_range = math.floor(data.shape[2] * testing_density)
    step = math.floor(data.shape[1] / x_range)
    
    # LOOP 1: scan & detect extreme values
    if (not skip_scanning):
        print("Scanning " + log_ratio +  str(base_count) + " (== " + str(actual_count) + ") rows to determine min and max values...")
        
        # Init minmax array (extremal values of positions, velocities... whatever)
        real_minmaxs = []
        for d in range(0, dimensionality):
            real_minmaxs.append([float("inf"), float("-inf")])
        
        i = 0
        logs_count = 0
        
        for a in range(0, x_range):
            for b in range(0, x_range):
                for c in range(0, z_range):
                    aa = a * step
                    bb = b * step
                    cc = c * step
                    
                    log_row = ""
                    
                    for d in range(0, dimensionality):
                        dimension_name = dimensions[d][0]
                        dimension_mode = dimensions[d][1]
                        
                        # Grab data
                        if (not is_cell_array):
                            val = data[aa][bb][cc]
                        else:
                            val = data[aa][bb][cc][d]
                        
                        # Checking mode
                        if (dimension_mode == "log"):
                            if (val <= 0):
                                val = float('-inf')
                            else:
                                val = math.log10(val)
                            
                        # Rounding (5 digits just for the scan)
                        
                        if (val != float('-inf')):
                            val = round_to_n(val, 5)
                        
                        # Update max value
                        if (val > real_minmaxs[d][1]):
                            real_minmaxs[d][1] = val
                            
                        # Update min value
                        if (val < real_minmaxs[d][0]):
                            real_minmaxs[d][0] = val
                            
                        # Feed row to potentially log
                        log_row = log_row + str(val) + " "
                        
                    # Maybe log
                    if ((i / actual_count) >= (logs_count / nb_logs)):
                        logs_count += 1
                        print(str(1 + i * step ** 3) + "th row values are: " + log_row)
                        
                    i += 1

        # Log detected extrema
        for d in range(0, dimensionality):
            dimension_name = dimensions[d][0]
            print("Min value for " + dimension_name + " is: " + str(real_minmaxs[d][0]))
            print("Max value for " + dimension_name + " is: " + str(real_minmaxs[d][1]))
        
        # Log scanning time
        mid_time = datetime.datetime.now()
        delta = mid_time.timestamp() - start_time.timestamp()
        print("Scanned data in: " + str(round(delta, 2)) + " seconds.")
    
    # LOOP 2: normalize so it fits max resolution
    print("Normalizing " + log_ratio + str(data.size) + " (== " + str(actual_count) + ") values, parsing to hex and writing to Texture3D Unity file...")
    print("Using following minmaxs array: " + str(minmaxs))
    
    max_resolution = (65536 - 1) if (quality == "high") else (256 - 1)
    
    j = 0
    logs_count = 0
    for a in range(0, x_range):
        for b in range(0, x_range):
            for c in range(0, z_range):
                aa = a * step
                bb = b * step
                cc = c * step
                
                log_row = ""
                
                for d in range(0, dimensionality):
                    dimension_name = dimensions[d][0]
                    dimension_mode = dimensions[d][1]
                    
                    # Get minmaxs
                    min_val = minmaxs[d][0]
                    max_val = minmaxs[d][1]

                    # Grab data
                    if (not is_cell_array):
                        val = data[aa][bb][cc]
                    else:
                        val = data[aa][bb][cc][d]
                    
                    # Checking mode
                    if (dimension_mode == "log"):
                        if (val <= 0):
                            val = min_val
                        else:
                            val = math.log10(val)
                        
                    # Remap
                    val = round(remap(val, min_val, max_val, 0, max_resolution, True))
                    hex_value = parse_int_to_formatted_hex(val, quality)
                    
                    # Write to file
                    destination_file.write(str(hex_value))
                    
                    # Feed row to potentially log
                    log_row = log_row + str(hex_value) + " "
                    
                # Maybe log
                if ((j / actual_count) >= (logs_count / nb_logs)):
                    logs_count += 1
                    print(str(1 + j * step ** 3) + "th row values are: " + log_row)
                    
                j += 1
    
    # Log normalizing time
    end_time = datetime.datetime.now()
    delta = end_time.timestamp() - (start_time.timestamp() if skip_scanning else mid_time.timestamp())
    print("Parsed and wrote data to file in: " + str(round(delta, 2)) + " seconds.")
    
    # Generate Unity footer
    write_unity_footer(destination_file)
    
    # Conclude
    print("File " + dest_file_name + ".asset was created")

# Count points in pointcloud to create 3D texture (voxel cloud), or add their density
def klodufy_txt (source_file, size, source_xyz_min, source_xyz_max, quality, dest_path, dest_file_name, testing_density, nb_logs):
    
    # Testing mode inits (the generated cube always has a dimension of size³ regardless of testing density
    testing_density = min(1, testing_density) # Make sure it don't go krazy (> 1)
    testing_value = round(1/testing_density)
    
    arr = np.loadtxt(source_file)
    leng = arr.shape[0]
    actual_count = math.floor(leng * testing_density)
    total_size = size * size * size
    
    #print("Source data shape is " + str(arr.shape))
    log_ratio = "all of " if testing_value == 1 else ("1 in " + str(testing_value) + " of all ")
    print("Source row count: " + str(leng))
    print("Browsing " + log_ratio + str(leng) + " (== " + str(actual_count) + ") points to generate Unity Texture3D file " + dest_file_name + ".txt of cube size " + str(size) + "³ = " + str(total_size) + "...")
    
    # Init empty 3D texture
    klodu = []
    voxel_size = (1 - 0) * 1 / size
    for c in range(0, total_size):
        klodu.append(0)
    
    # Prepare export file
    dest_file_name = dest_file_name + ("-HQ" if quality == "high" else "-LQ")
    destination_file = open("output/" + dest_path + dest_file_name + ".asset", "w")
    
    # Generate Unity header
    base_size = size
    dimensionality = 1
    write_unity_header(destination_file, dest_file_name, base_size, testing_density, dimensionality, quality)
    
    # Set max resolution for hex values
    max_resolution = (65536 - 1) if (quality == "high") else (256 - 1)
    
    # Loop into source data, find nearest voxel and increment its intensity
    # Also detect max value
    max_value = 0
    step = math.floor(testing_value)
    ii = 0
    for i in range(0, actual_count):
        ii = i * step
        line = arr[ii]
        x = line[0]
        y = line[1]
        z = line[2]
        v = line[3]
        xx = remap(x, source_xyz_min, source_xyz_max, 0, 1, False)
        yy = remap(y, source_xyz_min, source_xyz_max, 0, 1, False)
        zz = remap(z, source_xyz_min, source_xyz_max, 0, 1, False)
        vv = v
        
        # Get voxel index from remapped source position
        fix = int(xx / voxel_size) # floor
        fiy = int(yy  / voxel_size)
        fiz = int(zz / voxel_size)
        
        #print("klodu target indexes are (" + str(fix) + ", " + str(fiy) + ", " + str(fiz) + ")")
        
        # Fill target klodu with some value
        kx = fix
        ky = fiy * size
        kz = fiz * size * size
        k = kx + ky + kz
        klodu[k] += 1 # 10**(vv + 15)
        
        if (klodu[k] > max_value):
            max_value = klodu[k]
        
    print("Max value is " + str(max_value))
    
    # Normalize so it fits max resolution, parsing to hex and writing to file
    print("Normalizing (over " + str(len(klodu)) + " values), parsing to hex and writing to file...")
    for j in range (0, len(klodu)):
        klodu[j] = round(klodu[j] / max_value * max_resolution)
        
        # Write final klodu values to text file
        hex_value = parse_int_to_formatted_hex(klodu[j], quality)
        
        destination_file.write(str(hex_value))
        
        # Print out some values while waiting...
        if (j % int(len(klodu)/nb_logs) == 0):
            #print(str(klodu[j]) + " " + str(max_value) + " " + str(max_resolution))
            print(str(j + 1) + "th value is: " + str(hex_value) + " (" + str(100 * klodu[j] / max_resolution) + "% of max intensity)")
    
    # Now... time to smooth values by looking at neighbours...
    # Coming soon...
    
    # Generate Unity footer
    write_unity_footer(destination_file)
    
    print("Done!")

# DWARFGAL!
# Klodufy already cleaned Dwarfgal file
def klodufy_txt_dwarfgal ():
    source_file = "./output/dwarfgal/1-frame/dwarfgal-xyzrho.txt"
    size = 70
    source_xyz_min = 0
    source_xyz_max = 1000000
    quality = "low"
    dest_path = "dwarfgal/1-frame/"
    dest_file_name = "klo-dwarfgal-" + str(size)
    testing_density = 1/1
    nb_logs = 12
    
    klodufy_txt(source_file, size, source_xyz_min, source_xyz_max, quality, dest_path, dest_file_name, testing_density, nb_logs)
# klodufy_txt_dwarfgal()

# YOUNGDISK!
def klodufy_youngdisk_frame (frame, index):
    frame = prepend_zeros(str(frame), 5)
    index = prepend_zeros(str(index), 4)
    source_file = "./data/youngdisk/1864-frames/ang_mom_stack_" + str(frame) + ".npy"
    file_type_token = "NUMPY"
    size = 137
    dimensions = [ ["rho", "log"] ]
    minmaxs = [ [-18, -10] ]
    quality = "high"
    dest_path = "youngdisk/1864-frames/"
    dest_file_name = "klo-youngdisk-137-rho-" + str(index)
    testing_density = 1/40
    nb_logs = 10
    skip_scanning = False
    
    klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning)
# klodufy_youngdisk_frame (450, 999999)
def klodufy_youngdisk_full_anim():
    start_index = 460
    end_index = 460
    diff = end_index - start_index
    print("Generating " + str(diff) + " animation frames with density data...")
    
    i = start_index - 58
    for f in range(start_index, end_index + 1):
        i = i + 1
        klodufy_youngdisk_frame(f, i)
        
    print("Generated " + str(diff + 1) + " animation frames.")
# klodufy_youngdisk_full_anim()

# TIDALSTRIP!
def klodufy_tidalstrip_anim_frame (frame, index, type):
    print("Frame " + str(frame))
    print("Index " + str(index))
    print("Type " + type)
    
    if (type == "rho"):
        dimensions = [ ["rho", "log"] ]
        minmaxs = [ [1, 10] ]
        file_prefix = "density"
        
    elif (type == "vx" or type == "vy" or type == "vz"):
        dimensions = [ [type, "linear"] ]
        minmaxs = [ [-5, 5] ]
        
        if (type == "vx"):
            file_prefix = "velocity_x"
        elif (type == "vy"):
            file_prefix = "velocity_y"
        else:
            file_prefix = "velocity_z"
        
    else:
        print(error_start + "[klodufy_tidalstrip_anim_frame] Error - unknown type: " + type + error_end)
        
    # source_file = "./data/tidalstrip/high-res-test/" + type + "/" + file_prefix + "_output00" + str(frame) + "_GID0009_res128.dat"
    source_file = "./data/tidalstrip/high-res-frame/density_output00284_GID0009_res512.dat"
    file_type_token = "DAT"
    # size = 128
    size = 512
    quality = "high"
    dest_path = "tidalstrip/high-res-frame/"
    dest_file_name = "klo-tidal-" + type + "-" + str(size) + "-anim-" + prepend_zeros(str(index), 3)
    testing_density = 1/1 # 1/1 is full rendering
    nb_logs = 20
    skip_scanning = False
    
    klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning)
# klodufy_tidalstrip_anim_frame (284, 0, "rho")
def klodufy_tidalstrip_full_46_anim ():
    times = np.loadtxt("./data/tidalstrip/46-frames/filtered_times_all.txt")
    size = len(times)
    
    print("Generating " + str(size) + " animation frames with rho, vx, vy, and vz (" + str(4 * size) + " klodus in total)")
    
    for t in range(0, size):
        time = int(times[t][0])
        klodufy_tidalstrip_anim_frame(time, t + 1, "rho")
        klodufy_tidalstrip_anim_frame(time, t + 1, "vx")
        klodufy_tidalstrip_anim_frame(time, t + 1, "vy")
        klodufy_tidalstrip_anim_frame(time, t + 1, "vz")
        
    print("Generated " + str(size) + " animation frames.")
# klodufy_tidalstrip_full_46_anim()

# ISOLAGAL!
def klodufy_isolagal_gas ():

    dimensions = [ ["rho", "log"] ]
    minmaxs = [ [-8, 1] ]
    file_prefix = "density"

    source_file = "./data/isolagal/1-frame/isolagal_gas_cube.h5"
    file_type_token = "HDF5"
    size = 256
    quality = "high"
    dest_path = "isolagal/1-frame/"
    dest_file_name = "isolagal-gas-rho-" + str(size)
    testing_density = 1/1 # 1/1 is full rendering
    nb_logs = 20
    skip_scanning = True
    
    klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning)
# klodufy_isolagal_gas()

# FRED THOMPSON STAR CLUSTER (has xyz so extracted in particles_textufy)
def klodufy_fredthompson_starcluster ():

    dimensions = [ ["rho", "log"], ["x", "linear"], ["y", "linear"], ["z", "linear"] ]
    minmaxs = [ [-50, 50], [-50, 50], [-50, 50], [-50, 50] ]
    file_prefix = "density"

    source_file = "./data/fredthompson/H10cluster_8pc_output176_gas.h5"
    # source_file = "./data/fredthompson/H10cluster_8pc_output176_stars.h5"
    # source_file = "./data/fredthompson/H10cluster_8pc_output176_gas.h5"
    file_type_token = "HDF5"
    size = 256
    quality = "high"
    dest_path = "fredthompson/"
    dest_file_name = "fredthompson-starcluster-rho-" + str(size)
    testing_density = 1/10 # 1/1 is full rendering
    nb_logs = 20
    skip_scanning = False
    
    klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning)
# klodufy_fredthompson_starcluster()

# YOHANDUBOIS GALAXY
def klodufy_yohandubois_galaxy_rho ():
    dimensions = [ ["rho", "log"] ]
    minmaxs = [ [-7, -3] ]
    file_prefix = "density"

    source_file = "./data/yohandubois/1-frame/cube_gasdensity_output_00070.dat"
    file_type_token = "DAT"
    size = 128
    quality = "high"
    dest_path = "yohandubois/1-frame/"
    dest_file_name = "yohandubois-galaxy-rho-" + str(size)
    testing_density = 1/1 # 1/1 is full rendering
    nb_logs = 20
    skip_scanning = False
    
    klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning)
# klodufy_yohandubois_galaxy_rho ()
def klodufy_yohandubois_galaxy_bz ():
    dimensions = [ ["bz", "linear"] ]
    minmaxs = [ [-0.00001, 0.00001] ]
    file_prefix = "bz"

    source_file = "./data/yohandubois/1-frame/cube_bz_output_00070.dat"
    file_type_token = "DAT"
    size = 256
    quality = "high"
    dest_path = "yohandubois/1-frame/"
    dest_file_name = "yohandubois-galaxy-bz-" + str(size)
    testing_density = 1/1 # 1/1 is full rendering
    nb_logs = 20
    skip_scanning = False
    
    klodufy (source_file, file_type_token, size, dimensions, minmaxs, quality, dest_path, dest_file_name, testing_density, nb_logs, skip_scanning)
klodufy_yohandubois_galaxy_bz()
