# ANDRIX ® 2025-2026 🤙
# 
# Generate 2D textures (EXR files) from particle text data for Unity VFX Graph sampling
#
# This file calls texturify_2d.create_texture_2d() with various parameters to convert 
# text files (generated by fry_*.py scripts) into ready-to-use 2D texture images

from loguru import logger
from astrocutlery.texturify_2d import create_texture_2d


# San Han galaxy cluster
def plate_san_han_galaxy_cluster_xyzdensitytemp(is_test=False):
	"""
	Generate 2D EXR textures from San Han galaxy cluster particle text data.
	Requires text file generated by fry_shan_galaxy_cluster.textufy_san_han_galaxy_cluster_xyzdensitytemp()
	"""
	# Texture generation parameters
	# These define the min/max ranges used to normalize each data column
	# Columns: x, y, z, density, temperature
	array_of_mins = [0.0, 0.0, 0.0, 0.0, 0.0]
	array_of_maxs = [1.0e6, 1.0e6, 1.0e6, 1.0e3, 1.0e3]
	
	# File and path parameters
	source_author_folder = "sanhangalaxycluster"
	source_frames_folder = "1-frame"
	source_file_name = "sanhangalaxycluster-xyzdensitytemp-1-in-3" + ("-testing" if is_test else "")
	output_base_dir = "./output"
	
	logger.info(f"[plate_shan_galaxy_cluster] Starting texture generation for {source_file_name}")
	
	# Generate textures from text data
	create_texture_2d(source_author_folder, source_frames_folder, source_file_name, array_of_mins, array_of_maxs, output_base_dir)
	
	logger.info(f"[plate_shan_galaxy_cluster] Texture generation complete 👌")


if __name__ == "__main__":
	plate_san_han_galaxy_cluster_xyzdensitytemp()
